import type { BrandProfile } from '../types/brand'

/** Demo tenants mapped to the five Jifunze domains only. */
export const demoBrands: BrandProfile[] = [
  {
    id: 'jifunze-sustain',
    name: 'Jifunze Demo Co.',
    industry: 'Sustainable consumer products',
    audience_summary: 'Eco-conscious millennials who shop online and follow product drops.',
    voice: 'warm',
    banned_topics: ['politics', 'crypto investment advice'],
    competitor_keywords: ['greenwash', 'fast fashion'],
    priority_topics: ['sustainability', 'product launch', 'customer story', 'retail trends'],
    primaryDomain: 'lifestyle',
    secondaryDomains: ['entertainment'],
    allow_cross_domain_signals: true,
    allowed_trend_categories: [
      'cultural_moment',
      'local_event',
      'educational_topic',
      'industry_update',
      'product_launch',
      'viral_trend',
    ],
    forbidden_trend_categories: ['meme', 'breaking_news'],
    preferred_content_formats: [
      'carousel_concept',
      'single_static_graphic',
      'motion_poster',
      'caption_only_post',
    ],
    media_style: {
      palette_notes: 'moss green, warm paper white, charcoal ink',
      typography_notes: 'humanist sans, medium weight, generous line height',
      reference_mood: 'editorial sustainability report meets DTC drop',
      layout_bias: 'asymmetric grid with one hero panel',
    },
    visual_realism_preference: 'near_realistic',
    animation_preference: 'subtle_loop',
    creative_risk_level: 'balanced',
    geo_hint: 'North America',
    sensitive_review_keywords: ['recall', 'lawsuit', 'investigation'],
    automation: {
      auto_publish_enabled: false,
      minimum_priority_for_auto_queue: 0.48,
    },
    conversion: {
      primary_conversion_goal: 'traffic',
      secondary_conversion_goals: ['engagement', 'lead_generation'],
      destinations: {
        website_url: 'https://jifunze-demo.co',
        instagram_handle: 'jifunzedemo',
        product_link: 'https://jifunze-demo.co/shop',
        whatsapp_number: '+1-555-0100',
        booking_link: 'https://jifunze-demo.co/book',
      },
    },
  },
  {
    id: 'pulse-beauty',
    name: 'Pulse Beauty Lab',
    industry: 'Beauty & personal care',
    audience_summary: 'Gen Z creators who discover products through short video and peer reviews.',
    voice: 'playful',
    banned_topics: ['medical claims', 'weight loss promises'],
    competitor_keywords: ['copycat packaging'],
    priority_topics: ['texture shots', 'routine hacks', 'inclusive shade range'],
    primaryDomain: 'beauty',
    secondaryDomains: ['lifestyle', 'entertainment'],
    allowed_trend_categories: [
      'viral_trend',
      'product_launch',
      'cultural_moment',
      'celebrity_event',
      'educational_topic',
      'viral_audio',
    ],
    forbidden_trend_categories: ['breaking_news', 'meme'],
    preferred_content_formats: [
      'short_form_video_concept',
      'carousel_concept',
      'near_realistic_promo_visual',
      'caption_only_post',
    ],
    media_style: {
      palette_notes: 'glass skin highlights, soft orchid, chrome accents',
      typography_notes: 'condensed display for hooks, rounded UI for body',
      reference_mood: 'late-night vanity lighting, ASMR-adjacent calm',
      layout_bias: 'vertical 9:16 storyboard-first',
    },
    visual_realism_preference: 'near_realistic',
    animation_preference: 'expressive_motion',
    creative_risk_level: 'bold',
    geo_hint: 'Global English-speaking',
    sensitive_review_keywords: ['fda', 'clinical', 'before and after claims'],
    automation: {
      auto_publish_enabled: true,
      minimum_confidence_for_auto_publish: 0.86,
      minimum_priority_for_auto_queue: 0.58,
      allowed_auto_publish_categories: ['product_launch', 'cultural_moment', 'educational_topic'],
    },
    conversion: {
      primary_conversion_goal: 'lead_generation',
      secondary_conversion_goals: ['sales', 'engagement'],
      destinations: {
        instagram_handle: 'pulsebeautylab',
        booking_link: 'https://pulsebeauty.example/book',
        whatsapp_number: '+1-555-0199',
        website_url: 'https://pulsebeauty.example',
        product_link: 'https://pulsebeauty.example/new-drop',
      },
    },
  },
  {
    id: 'nocturne-events',
    name: 'Nocturne Collective',
    industry: 'Live experiences & nightlife promotion',
    audience_summary: 'Urban professionals 24–38 who buy tickets week-of and share clips same-night.',
    voice: 'bold',
    banned_topics: ['illegal substances', 'unsafe crowd behavior'],
    competitor_keywords: ['unlicensed venues'],
    priority_topics: ['lineups', 'limited capacity', 'city takeovers'],
    primaryDomain: 'music',
    secondaryDomains: ['entertainment', 'lifestyle'],
    allowed_trend_categories: [
      'viral_audio',
      'viral_trend',
      'local_event',
      'celebrity_event',
      'cultural_moment',
      'industry_update',
    ],
    forbidden_trend_categories: ['educational_topic'],
    preferred_content_formats: [
      'motion_poster',
      'animation_concept',
      'short_form_video_concept',
      'carousel_concept',
    ],
    media_style: {
      palette_notes: 'deep violet, laser cyan, matte black',
      typography_notes: 'wide grotesk headlines, monospace for metadata',
      reference_mood: 'warehouse haze, strobe silhouettes, kinetic type',
      layout_bias: 'full-bleed poster with bold diagonal grid',
    },
    visual_realism_preference: 'stylized',
    animation_preference: 'expressive_motion',
    creative_risk_level: 'bold',
    geo_hint: 'Major metros EU + US',
    automation: {
      auto_queue_enabled: true,
      auto_draft_enabled: true,
      auto_publish_enabled: false,
      minimum_priority_for_auto_queue: 0.5,
    },
    conversion: {
      primary_conversion_goal: 'sales',
      secondary_conversion_goals: ['lead_generation', 'traffic'],
      destinations: {
        website_url: 'https://nocturne.example',
        instagram_handle: 'nocturne.collective',
        booking_link: 'https://tix.nocturne.example',
        product_link: 'https://tix.nocturne.example/vip',
        whatsapp_number: '+44-20-5550-1234',
      },
    },
  },
]
