import type { BrandProfile } from '../types/brand'

/** Demo tenants: AI educators / creators (tutorials, tool explainers, audience growth). */
export const demoBrands: BrandProfile[] = [
  {
    id: 'jifunze-ai-studio',
    name: 'Jifunze AI Studio',
    industry: 'AI education & creator tools',
    audience_summary:
      'Creators and professionals who teach AI tools, explain concepts in plain language, and grow followings around practical AI literacy.',
    voice: 'warm',
    banned_topics: ['politics', 'crypto investment advice', 'unverified medical claims'],
    competitor_keywords: ['clickbait AI hype', 'get-rich-quick automation'],
    priority_topics: [
      'tool walkthrough',
      'step-by-step tutorial',
      'model or API comparison',
      'real-world use case',
      'beginner breakdown',
      'prompt patterns',
      'safety and limitations',
    ],
    primaryDomain: 'ai',
    secondaryDomains: [],
    allow_cross_domain_signals: false,
    allowed_trend_categories: [
      'educational_topic',
      'industry_update',
      'product_launch',
      'cultural_moment',
      'viral_trend',
      'viral_audio',
    ],
    forbidden_trend_categories: ['meme', 'celebrity_event', 'breaking_news'],
    preferred_content_formats: [
      'short_form_video_concept',
      'carousel_concept',
      'caption_only_post',
      'motion_poster',
    ],
    media_style: {
      palette_notes: 'electric violet, slate, paper white accents',
      typography_notes: 'clean geometric sans; large step numbers for carousels',
      reference_mood: 'screen-recording friendly studio: UI demos, diagrams, minimal chrome',
      layout_bias: 'vertical 9:16 with clear chapter frames; carousel grids for steps',
    },
    visual_realism_preference: 'near_realistic',
    animation_preference: 'subtle_loop',
    creative_risk_level: 'balanced',
    geo_hint: 'Global English-speaking',
    sensitive_review_keywords: ['lawsuit', 'security breach', 'child safety'],
    automation: {
      auto_publish_enabled: false,
      minimum_priority_for_auto_queue: 0.48,
    },
    conversion: {
      primary_conversion_goal: 'lead_generation',
      secondary_conversion_goals: ['engagement', 'traffic'],
      destinations: {
        website_url: 'https://jifunze-ai.example',
        instagram_handle: 'jifunzeaistudio',
        product_link: 'https://jifunze-ai.example/courses',
        whatsapp_number: '+1-555-0100',
        booking_link: 'https://jifunze-ai.example/office-hours',
      },
    },
  },
  {
    id: 'context-weights',
    name: 'Context & Weights',
    industry: 'Technical AI literacy for builders',
    audience_summary:
      'Developers and power users who want deeper breakdowns: architecture sketches, eval tips, and honest trade-offs between tools.',
    voice: 'professional',
    banned_topics: ['politics', 'financial advice'],
    competitor_keywords: ['vaporware', 'undisclosed sponsorship'],
    priority_topics: [
      'architecture breakdown',
      'benchmark or comparison',
      'API walkthrough',
      'evaluation methodology',
      'cost and latency trade-offs',
    ],
    primaryDomain: 'ai',
    secondaryDomains: [],
    allow_cross_domain_signals: false,
    allowed_trend_categories: [
      'educational_topic',
      'industry_update',
      'product_launch',
      'cultural_moment',
      'viral_trend',
    ],
    forbidden_trend_categories: ['meme', 'celebrity_event', 'breaking_news', 'viral_audio'],
    preferred_content_formats: [
      'carousel_concept',
      'caption_only_post',
      'short_form_video_concept',
      'single_static_graphic',
    ],
    media_style: {
      palette_notes: 'graph paper grey, signal green, ink black',
      typography_notes: 'monospace for code paths; restrained display for headlines',
      reference_mood: 'whiteboard + terminal: diagrams, bullets, no lifestyle filler',
      layout_bias: 'carousel-first explainers; wide cards for comparison tables',
    },
    visual_realism_preference: 'near_realistic',
    animation_preference: 'subtle_loop',
    creative_risk_level: 'balanced',
    geo_hint: 'Remote-first',
    sensitive_review_keywords: ['security vulnerability', 'exploit'],
    automation: {
      auto_publish_enabled: false,
      minimum_confidence_for_auto_publish: 0.86,
      minimum_priority_for_auto_queue: 0.58,
      allowed_auto_publish_categories: ['educational_topic', 'industry_update', 'product_launch'],
    },
    conversion: {
      primary_conversion_goal: 'traffic',
      secondary_conversion_goals: ['lead_generation', 'engagement'],
      destinations: {
        instagram_handle: 'contextweights',
        booking_link: 'https://contextweights.example/office-hours',
        whatsapp_number: '+1-555-0199',
        website_url: 'https://contextweights.example',
        product_link: 'https://contextweights.example/newsletter',
      },
    },
  },
]
